### ISSUE TITLE
ScalerCH needs some documentation

### ISSUE THREAD

**Issue by prjemian** [bluesky/ophyd#591]
There is zero documentation about this device.  It's an improvement over `EpicsScaler`, right?  Ready for production use?

**Comment by danielballan** [comment]
> There is zero documentation about this device.

Ugh, sorry. I'll work on that and use this issue to track it.

> It's an improvement over EpicsScaler, right? 

Yes. The layout of the components is more natural, in our opinion.

> Ready for production use?

Yes, used in production at multiple NSLS-II beamlines.

**Comment by danielballan** [comment]
@prjemian To tide you over, an example in production: https://github.com/NSLS-II-TES/profile_collection/blob/master/startup/25-sclr.py

**Comment by tacaswell** [comment]
Scalers present a particularly challenging surface for ophyd.  It seems to be that the MCA mode and the 'normal counting' mode are more-or-less orthogonal sets of controls that talk to the same underlying hardware (hence the sorta-hacky 'set_mode' stuff).  You want to make the separate devices because their logic / PVs / etc are separate, but the same device to ensure you do not try to use both 'views' in the same scan.

**Comment by prjemian** [comment]
Thanks.

APS USAXS will use [`ScalerCH`](https://github.com/APS-USAXS/ipython-usaxs/issues/37)

Here's a tutorial for `ScalerCH`, written for the absolute novice (who conveniently happens to have a synApps 5.8 scaler record nearby):
https://github.com/BCDA-APS/use_bluesky/blob/master/notebooks/lesson1.ipynb

**Comment by prjemian** [comment]
USAXS: https://github.com/APS-USAXS/ipython-usaxs/blob/master/profile_bluesky/startup/20-detectors.py#L10
